# Generated by Django 6.0.5 on 2026-05-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_dailystreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='target_days',
            field=models.IntegerField(default=30),
        ),
    ]
